### UDsb1 Physical Eval

#### Preprocessing

In [33]:
import pandas as pd
import numpy as np

In [34]:
df = pd.read_csv("OASIS3_UDSb1_physical_eval.csv")

In [35]:
# # Import the necessary module
# from ydata_profiling import ProfileReport

# # Create a ProfileReport object
# report = ProfileReport(df)

# # Generate the data profiling report
# report.to_file('oasis_3_report.html')

In [36]:
df.isnull().sum()

OASISID                   0
OASIS_session_label       0
days_to_visit             0
age at visit              0
WEIGHT                 1003
HEIGHT                 1763
BPSYS                  1027
BPDIAS                 1034
HRATE                  1859
VISION                 1848
VISCORR                1850
VISWCORR               3159
HEARING                1849
HEARAID                1858
HEARWAID               7442
dtype: int64

In [37]:
df.shape

(8626, 15)

In [38]:
df.drop('HEARWAID', axis=1, inplace=True)

In [39]:
# impute the missing values to the mean of the column
df.fillna(df.mean(), inplace=True)

C:\Users\Ananya\AppData\Local\Temp\ipykernel_22368\3216825617.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)


In [40]:
df.isnull().sum()

OASISID                0
OASIS_session_label    0
days_to_visit          0
age at visit           0
WEIGHT                 0
HEIGHT                 0
BPSYS                  0
BPDIAS                 0
HRATE                  0
VISION                 0
VISCORR                0
VISWCORR               0
HEARING                0
HEARAID                0
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   OASISID              8626 non-null   object 
 1   OASIS_session_label  8626 non-null   object 
 2   days_to_visit        8626 non-null   int64  
 3   age at visit         8626 non-null   float64
 4   WEIGHT               8626 non-null   float64
 5   HEIGHT               8626 non-null   float64
 6   BPSYS                8626 non-null   float64
 7   BPDIAS               8626 non-null   float64
 8   HRATE                8626 non-null   float64
 9   VISION               8626 non-null   float64
 10  VISCORR              8626 non-null   float64
 11  VISWCORR             8626 non-null   float64
 12  HEARING              8626 non-null   float64
 13  HEARAID              8626 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 943.6+ KB


In [42]:
# convert days_to_visit to float
df['days_to_visit'] = df['days_to_visit'].astype(float)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   OASISID              8626 non-null   object 
 1   OASIS_session_label  8626 non-null   object 
 2   days_to_visit        8626 non-null   float64
 3   age at visit         8626 non-null   float64
 4   WEIGHT               8626 non-null   float64
 5   HEIGHT               8626 non-null   float64
 6   BPSYS                8626 non-null   float64
 7   BPDIAS               8626 non-null   float64
 8   HRATE                8626 non-null   float64
 9   VISION               8626 non-null   float64
 10  VISCORR              8626 non-null   float64
 11  VISWCORR             8626 non-null   float64
 12  HEARING              8626 non-null   float64
 13  HEARAID              8626 non-null   float64
dtypes: float64(12), object(2)
memory usage: 943.6+ KB


### Taking dx1 column from b4

#### Preprocessing

In [44]:
df2 = pd.read_csv("OASIS3_UDSb4_cdr.csv")

In [45]:
df2.shape

(8626, 23)

##### Checking Skewness

In [46]:
# %matplotlib inline

# import matplotlib.pyplot as plt

# # Your plotting code here

# plt.show()  # Display the plot in the Jupyter Notebook output


In [47]:
# create a new dataframe with only the columns we need
df2 = df2[['OASIS_session_label', 'dx1']]


In [48]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8626 entries, 0 to 8625
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   OASIS_session_label  8626 non-null   object
 1   dx1                  8625 non-null   object
dtypes: object(2)
memory usage: 134.9+ KB


In [49]:
df2.head()

OASIS_session_label                 dx1
0  OAS30001_UDSb4_d0000  Cognitively normal
1  OAS30001_UDSb4_d0339  Cognitively normal
2  OAS30001_UDSb4_d0722  Cognitively normal
3  OAS30001_UDSb4_d1106  Cognitively normal
4  OAS30001_UDSb4_d1456  Cognitively normal

In [50]:
df.head()

OASISID   OASIS_session_label  days_to_visit  age at visit  WEIGHT  \
0  OAS30001  OAS30001_UDSb1_d0000            0.0         65.19   999.0   
1  OAS30001  OAS30001_UDSb1_d0339          339.0         66.12   155.0   
2  OAS30001  OAS30001_UDSb1_d0722          722.0         67.17   162.0   
3  OAS30001  OAS30001_UDSb1_d1106         1106.0         68.22   167.0   
4  OAS30001  OAS30001_UDSb1_d1456         1456.0         69.18   173.0   

   HEIGHT  BPSYS  BPDIAS  HRATE  VISION  VISCORR  VISWCORR  HEARING  HEARAID  
0   999.0  138.0    70.0   72.0     1.0      1.0       1.0      1.0      0.0  
1    64.0  138.0    72.0   78.0     0.0      1.0       1.0      1.0      0.0  
2    64.0  144.0    80.0   60.0     0.0      1.0       1.0      1.0      0.0  
3    63.5  130.0    82.0   68.0     0.0      1.0       1.0      1.0      0.0  
4    63.5  142.0    70.0   72.0     1.0      1.0       1.0      1.0      0.0

##### Merging

In [51]:
# merge the two dataframes, df and df2, on OASIS_session_label based on the first 8 characters and last 5 characters
# Extract the first 8 characters and last 5 characters from 'OASIS_session_label' in both dataframes
df['OASIS_session_label_first8'] = df['OASIS_session_label'].str[:8]
df['OASIS_session_label_last5'] = df['OASIS_session_label'].str[-5:]
df2['OASIS_session_label_first8'] = df2['OASIS_session_label'].str[:8]
df2['OASIS_session_label_last5'] = df2['OASIS_session_label'].str[-5:]

# Merge the dataframes based on the first 8 and last 5 characters
df_final = df.merge(df2, on=['OASIS_session_label_first8', 'OASIS_session_label_last5'], how='inner')

# Drop the temporary columns if needed
df_final.drop(['OASIS_session_label_first8', 'OASIS_session_label_last5'], axis=1, inplace=True)

In [52]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8602 entries, 0 to 8601
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   OASISID                8602 non-null   object 
 1   OASIS_session_label_x  8602 non-null   object 
 2   days_to_visit          8602 non-null   float64
 3   age at visit           8602 non-null   float64
 4   WEIGHT                 8602 non-null   float64
 5   HEIGHT                 8602 non-null   float64
 6   BPSYS                  8602 non-null   float64
 7   BPDIAS                 8602 non-null   float64
 8   HRATE                  8602 non-null   float64
 9   VISION                 8602 non-null   float64
 10  VISCORR                8602 non-null   float64
 11  VISWCORR               8602 non-null   float64
 12  HEARING                8602 non-null   float64
 13  HEARAID                8602 non-null   float64
 14  OASIS_session_label_y  8602 non-null   object 
 15  dx1 

In [53]:
df_final.head()

OASISID OASIS_session_label_x  days_to_visit  age at visit  WEIGHT  \
0  OAS30001  OAS30001_UDSb1_d0000            0.0         65.19   999.0   
1  OAS30001  OAS30001_UDSb1_d0339          339.0         66.12   155.0   
2  OAS30001  OAS30001_UDSb1_d0722          722.0         67.17   162.0   
3  OAS30001  OAS30001_UDSb1_d1106         1106.0         68.22   167.0   
4  OAS30001  OAS30001_UDSb1_d1456         1456.0         69.18   173.0   

   HEIGHT  BPSYS  BPDIAS  HRATE  VISION  VISCORR  VISWCORR  HEARING  HEARAID  \
0   999.0  138.0    70.0   72.0     1.0      1.0       1.0      1.0      0.0   
1    64.0  138.0    72.0   78.0     0.0      1.0       1.0      1.0      0.0   
2    64.0  144.0    80.0   60.0     0.0      1.0       1.0      1.0      0.0   
3    63.5  130.0    82.0   68.0     0.0      1.0       1.0      1.0      0.0   
4    63.5  142.0    70.0   72.0     1.0      1.0       1.0      1.0      0.0   

  OASIS_session_label_y                 dx1  
0  OAS30001_UDSb4_d0000  Cognitively normal  
1  OAS30001_UDSb4_d0339  Cognitively normal  
2  OAS30001_UDSb4_d0722  Cognitively normal  
3  OAS30001_UDSb4_d1106  Cognitively normal  
4  OAS30001_UDSb4_d1456  Cognitively normal

In [54]:
# store df_final as a csv file
df_final.to_csv('OASIS3_UDSb1_merged.csv', index=False)

In [55]:
# # Import the necessary module
# from ydata_profiling import ProfileReport

# # Create a ProfileReport object
# report = ProfileReport(df)

# # Generate the data profiling report
# report.to_file('merged_report.html')

In [56]:
df_final.drop('OASIS_session_label_x', axis=1, inplace=True)

In [57]:
df_final.drop('OASIS_session_label_y', axis=1, inplace=True)

In [58]:
df_final.drop('OASISID', axis=1, inplace=True)

In [59]:
df_final.head()

days_to_visit  age at visit  WEIGHT  HEIGHT  BPSYS  BPDIAS  HRATE  VISION  \
0            0.0         65.19   999.0   999.0  138.0    70.0   72.0     1.0   
1          339.0         66.12   155.0    64.0  138.0    72.0   78.0     0.0   
2          722.0         67.17   162.0    64.0  144.0    80.0   60.0     0.0   
3         1106.0         68.22   167.0    63.5  130.0    82.0   68.0     0.0   
4         1456.0         69.18   173.0    63.5  142.0    70.0   72.0     1.0   

   VISCORR  VISWCORR  HEARING  HEARAID                 dx1  
0      1.0       1.0      1.0      0.0  Cognitively normal  
1      1.0       1.0      1.0      0.0  Cognitively normal  
2      1.0       1.0      1.0      0.0  Cognitively normal  
3      1.0       1.0      1.0      0.0  Cognitively normal  
4      1.0       1.0      1.0      0.0  Cognitively normal

In [60]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8602 entries, 0 to 8601
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   days_to_visit  8602 non-null   float64
 1   age at visit   8602 non-null   float64
 2   WEIGHT         8602 non-null   float64
 3   HEIGHT         8602 non-null   float64
 4   BPSYS          8602 non-null   float64
 5   BPDIAS         8602 non-null   float64
 6   HRATE          8602 non-null   float64
 7   VISION         8602 non-null   float64
 8   VISCORR        8602 non-null   float64
 9   VISWCORR       8602 non-null   float64
 10  HEARING        8602 non-null   float64
 11  HEARAID        8602 non-null   float64
 12  dx1            8601 non-null   object 
dtypes: float64(12), object(1)
memory usage: 940.8+ KB


##### Encoding

In [61]:
# encode column dx1 to numeric values. Label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_final['dx1'] = le.fit_transform(df_final['dx1'])

df_final.head()


days_to_visit  age at visit  WEIGHT  HEIGHT  BPSYS  BPDIAS  HRATE  VISION  \
0            0.0         65.19   999.0   999.0  138.0    70.0   72.0     1.0   
1          339.0         66.12   155.0    64.0  138.0    72.0   78.0     0.0   
2          722.0         67.17   162.0    64.0  144.0    80.0   60.0     0.0   
3         1106.0         68.22   167.0    63.5  130.0    82.0   68.0     0.0   
4         1456.0         69.18   173.0    63.5  142.0    70.0   72.0     1.0   

   VISCORR  VISWCORR  HEARING  HEARAID  dx1  
0      1.0       1.0      1.0      0.0   25  
1      1.0       1.0      1.0      0.0   25  
2      1.0       1.0      1.0      0.0   25  
3      1.0       1.0      1.0      0.0   25  
4      1.0       1.0      1.0      0.0   25

In [62]:
# check the uniqueness of dx1
df_final['dx1'].unique()

array([25, 51,  2, 48, 18,  9, 12, 43, 11,  3,  0, 42, 26, 38, 52, 49, 16,
        1, 40,  8,  7, 15, 19, 35, 41, 37, 17, 47, 32, 20, 13,  4,  5, 27,
       44, 36, 22, 45,  6, 50, 21, 34, 29, 28, 33, 53, 10, 46, 23, 14, 24,
       30, 31, 39])

In [63]:
df_final['dx1'].value_counts()

25    6386
2     1141
51     474
48      78
35      47
18      46
0       43
42      37
17      25
49      24
41      23
1       23
26      19
38      19
37      18
52      18
43      17
5       16
3       14
13      13
16      12
12      10
4       10
19      10
47       7
15       7
7        6
9        6
6        6
20       5
44       4
40       4
23       3
34       3
50       3
11       3
27       2
21       2
30       2
24       2
36       1
10       1
31       1
14       1
8        1
46       1
33       1
53       1
22       1
28       1
29       1
32       1
45       1
39       1
Name: dx1, dtype: int64

In [64]:
# split the data into train and test sets
from sklearn.model_selection import train_test_split

x = df_final.drop('dx1', axis=1)
y = df_final['dx1']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

##### Logistic Regression

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
model = LogisticRegression()
model.fit(x_train, y_train)
predictions = model.predict(x_test)

accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.2f}")
conf_matrix = confusion_matrix(y_test, predictions)
print("Confusion Matrix:")
print(conf_matrix)

# log = {'model': 'Logistic Regression', 'accuracy': accuracy}
# csv_logger.log(log)

Accuracy: 0.74
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


C:\Users\Ananya\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


##### RNN

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Step 1: Import the pre-made RNN model (e.g., nn.RNN or nn.LSTM)
from torch.nn import LSTM

# Step 2: Replace the custom RNN model with the pre-made model
class RNNModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNNModel, self).__init()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.rnn = LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)
        out, _ = self.rnn(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out

# Step 3: Update model architecture, hyperparameters, and training
input_size = 28
hidden_size = 128
num_layers = 2
num_classes = 10
learning_rate = 0.001
num_epochs = 5

model = RNNModel(input_size, hidden_size, num_layers, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Training loop
num_epochs =  # Number of training epochs
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Evaluation
model.eval()
with torch.no_grad():
    test_outputs = model(test_inputs)
    _, predicted = torch.max(test_outputs, 1)

# Calculate accuracy and F1 score
accuracy = accuracy_score(test_labels, predicted)
f1 = f1_score(test_labels, predicted, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"F1 Score: {f1}")
